name: VIP Scans and other code checks
on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - '*'

  workflow_call:

  workflow_dispatch:
    inputs:
      debug_enabled_code_check:
        type: boolean
        description: 'Enable "tmate" debugging for the code check'
        required: false
        default: false
jobs:
  check:
    name: Check the code
    runs-on: ubuntu-latest
    container:
      image: publishpress/dev-workspace-terminal:future-free-2
      options: -v ${{ github.workspace }}:/project --workdir="/project"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup tmate session for Debugging, if inputs.debug_enabled_code_check is true
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.debug_enabled_code_check }}
        timeout-minutes: 10
        with:
          detached: true

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Composer install
        run: composer install --no-interaction --no-progress --prefer-dist --ignore-platform-reqs

      - name: Build the package to a dir
        run: composer build:dir

      - name: PHPLint - Check PHP syntax errors
        run: composer check:lint

      - name: PHP - Check PHP compatibility
        run: composer check:php

      - name: PHPCS - Check VIP scan and code standards
        run: composer check:phpcs
