name: POT file check
on:
  push:
    branches:
      - 'develop'

  pull_request:
    branches:
      - '*'

  workflow_call:

  workflow_dispatch:
    inputs:
      tmate_enabled:
        type: boolean
        description: 'Enable "tmate" for debugging'
        required: false
        default: false
jobs:
  check:
    name: Check the POT file
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session for Debugging, if inputs.tmate_enabled is true
        uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.tmate_enabled }}
        timeout-minutes: 10
        with:
          detached: true

      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Prepare composer
        run: |
          $GITHUB_WORKSPACE/dev-workspace/run composer validate
          $GITHUB_WORKSPACE/dev-workspace/run composer install

      - name: Show version of tools inside the dev-workspace
        run: |
          $GITHUB_WORKSPACE/dev-workspace/run composer info:versions

      - name: Run POT file check
        run: |
          $GITHUB_WORKSPACE/dev-workspace/run composer check:pot-diff
          if [ $? -eq 1 ]; then
            gh issue create \
              --title "POT file has changes that need to be reviewed" \
              --body "The POT file check detected changes between the main branch and the current branch. Please review and update the PO files. cc: @andergmartins @stevejburge" \
              --label "translation" \
              --assignee "wocmultimedia"
          fi
